# fly.toml file generated for stewie1570-tetris on 2022-08-26T11:29:09-06:00

app = "stewie1570-tetris"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[memory]
  limit = 230000000

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25000
    soft_limit = 20000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
