name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build
    - name: Test Backend
      run: |
        dotnet test Tetris.Core.Tests/Tetris.Core.Tests.csproj
        dotnet test Tetris.Domain.Tests/Tetris.Domain.Tests.csproj
        dotnet test Tetris.Tests/Tetris.Tests.csproj
    - name: Test Frontend
      run: |
        cd Tetris/ClientApp
        yarn
        yarn test
    - name: Analyze Client App Size
      run: |
        cd Tetris/ClientApp
        yarn build
        yarn analyze
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
