name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build
    - name: Test Backend
      run: |
        dotnet test Tetris.Core.Tests/Tetris.Core.Tests.csproj
        dotnet test Tetris.Domain.Tests/Tetris.Domain.Tests.csproj
        dotnet test Tetris.Tests/Tetris.Tests.csproj
    - name: Test Frontend
      run: |
        cd Tetris/ClientApp
        yarn
        yarn test
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: Tetris/ClientApp/coverage/lcov-report/
    - name: Analyze Client App Size
      run: |
        cd Tetris/ClientApp
        yarn build
        yarn analyze
