name: Build (Merge)

on:
  push:
    branches: [master]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.*.*
      - name: Test Backend
        run: |
          dotnet restore
          dotnet build
          dotnet test Tetris.Core.Tests/Tetris.Core.Tests.csproj --no-build --verbosity normal
          dotnet test Tetris.Domain.Tests/Tetris.Domain.Tests.csproj  --no-build --verbosity normal
          dotnet test Tetris.Tests/Tetris.Tests.csproj  --no-build --verbosity normal

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Frontend
        run: |
          cd Tetris/ClientApp
          yarn
          yarn test

  test-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.*.*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm test

  version:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend, test-e2e]
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  publish-artifacts:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.*.*
      - name: Publish
        run: |
          cd Tetris/
          dotnet publish -c Release -o out
      - name: Upload Tetris Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tetris
          path: /home/runner/work/tetris/tetris/Tetris/out

  # deploy-to-fly:
  #   # Temporarily disabled due to fly.io not being reliable.
  #   if: false
  #   runs-on: ubuntu-latest
  #   needs: [version]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Find Release Version
  #       run: |
  #         git fetch --prune --unshallow
  #         echo "RELEASE_VERSION=$(git describe --tags --abbrev=0 | sed 's/v//').0" >> $GITHUB_ENV
  #     - uses: superfly/flyctl-actions/setup-flyctl@master
  #     - name: deploy
  #       env:
  #         RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
  #       run: flyctl deploy --no-cache --build-arg RELEASE_VERSION=${{ env.RELEASE_VERSION }} --build-arg NEWRELIC_KEY=${{ secrets.NEWRELIC_KEY }}

  # test-fly:
  #   # Temporarily disabled due to fly.io not being reliable.
  #   if: false
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   needs: [deploy-to-fly]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps

  #     - name: Run Playwright tests
  #       run: npm run test-fly

  #     - name: Upload test report
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30

