name: Build (PR)

on: [pull_request]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.*.*
      - name: Test Backend
        run: |
          dotnet restore
          dotnet build
          dotnet test Tetris.Core.Tests/Tetris.Core.Tests.csproj --no-build --verbosity normal
          dotnet test Tetris.Domain.Tests/Tetris.Domain.Tests.csproj  --no-build --verbosity normal
          dotnet test Tetris.Tests/Tetris.Tests.csproj  --no-build --verbosity normal

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Frontend
        run: |
          cd Tetris/ClientApp
          yarn
          yarn test

  smoke-test:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Test Frontend (via Mac)
        run: |
          cd Tetris/ClientApp
          yarn
          yarn test
          yarn build
